name: OmniQA CI
on:
  push: { branches: [ main ] }
  pull_request: {}
env:
  BASE_URL: https://the-internet.herokuapp.com
  API_BASE_URL: https://jsonplaceholder.typicode.com
  HEADLESS: "true"

jobs:
  pw-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: |
          cd playwright-typescript
          npm ci
          npx playwright install --with-deps
          npx playwright test --reporter=html
      - uses: actions/upload-artifact@v4
        with: { name: pw-ts-report, path: playwright-typescript/playwright-report }
      - uses: actions/upload-artifact@v4
        with: { name: pw-ts-artifacts, path: playwright-typescript/test-artifacts, if-no-files-found: ignore }

  pw-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          pip install -r playwright-python/requirements.txt
          python -m playwright install --with-deps
          pytest playwright-python/tests --html=playwright-python/report/index.html --self-contained-html
      - uses: actions/upload-artifact@v4
        with: { name: pw-py-report, path: playwright-python/report }
      - uses: actions/upload-artifact@v4
        with: { name: pw-py-artifacts, path: playwright-python/test-artifacts, if-no-files-found: ignore }

  sel-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          pip install -r selenium-python/requirements.txt
          pytest selenium-python/tests --html=selenium-python/report/index.html --self-contained-html
      - uses: actions/upload-artifact@v4
        with: { name: sel-py-report, path: selenium-python/report }

  build-site:
    runs-on: ubuntu-latest
    needs: [pw-ts, pw-py, sel-py]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { path: _artifacts }
      - run: |
          rm -rf site && mkdir -p site/reports
          cp -r _artifacts/pw-ts-report site/reports/playwright-typescript || true
          cp -r _artifacts/pw-ts-artifacts site/reports/playwright-typescript-artifacts || true
          cp -r _artifacts/pw-py-report site/reports/playwright-python || true
          cp -r _artifacts/pw-py-artifacts site/reports/playwright-python-artifacts || true
          cp -r _artifacts/sel-py-report site/reports/selenium-python || true
          cat > site/index.html <<'HTML'
          <!doctype html><html><head>
            <meta charset="utf-8" />
            <title>OmniQA Lab — Latest Reports</title>
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <style>body{font:16px/1.6 system-ui;margin:2rem;max-width:960px}a{display:block;margin:.5rem 0}</style>
          </head><body>
            <h1>OmniQA Lab — Latest CI Reports</h1>
            <p>Updates on every push to <code>main</code>. Playwright captures videos/screenshots/traces.</p>
            <h2>UI & API</h2>
            <a href="reports/playwright-typescript/index.html">Playwright (TypeScript) — HTML report</a>
            <a href="reports/playwright-typescript-artifacts/">Playwright (TypeScript) — videos/screenshots/traces</a>
            <a href="reports/playwright-python/index.html">Playwright (Python) — HTML report</a>
            <a href="reports/playwright-python-artifacts/">Playwright (Python) — videos/screenshots/traces</a>
            <a href="reports/selenium-python/index.html">Selenium (Python) — HTML report</a>
            <h2>Manual Tests</h2>
            <a href="../manual-tests/test-cases.md">Manual test cases (Markdown)</a>
          </body></html>
          HTML
      - uses: actions/upload-pages-artifact@v3
        with: { path: site }

  deploy:
    runs-on: ubuntu-latest
    needs: build-site
    permissions: { pages: write, id-token: write }
    environment: { name: github-pages }
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4